# Generated by Django 5.0.4 on 2026-03-25 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('hotel_data', models.JSONField(blank=True, default=dict)),
                ('activities_data', models.JSONField(blank=True, default=list)),
                ('food_data', models.JSONField(blank=True, default=list)),
                ('transport_data', models.JSONField(blank=True, default=dict)),
                ('day_cost_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('place_type', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('image_keyword', models.CharField(max_length=200)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('total_days', models.PositiveIntegerField(default=3)),
                ('budget_inr', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('budget_used_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_preference', models.CharField(default='INR', max_length=3)),
                ('travel_style', models.JSONField(blank=True, default=list)),
                ('travelers_count', models.PositiveIntegerField(default=1)),
                ('travel_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('shared', 'Shared')], default='draft', max_length=20)),
                ('itinerary_json', models.JSONField(blank=True, default=dict)),
                ('language_preference', models.CharField(default='en', max_length=10)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
